# Auto-generated by build_dashboard_source(). Do not hand-edit.
from prefab_ui.app import PrefabApp
from prefab_ui.components import (
    Badge, Card, CardContent, CardHeader, CardTitle,
    Column, H1, H2, H3, Muted, Row, Tab, Tabs, Text,
)
from prefab_ui.components.charts import (
    BarChart, ChartSeries, PieChart,
)

with PrefabApp(css_class="max-w-5xl mx-auto p-6") as app:
    with Card():
        with CardHeader():
            CardTitle("Travel Atlas — countries to visit from India")
        with CardContent():
            with Column(gap=5):
                with Row(gap=5):
                    with Column(gap=1):
                        Muted("Recommendation sets")
                        H1('2')
                        Muted("recommendations.json")
                    with Column(gap=1):
                        Muted("Countries surfaced")
                        H1('12')
                        Muted('across 2 regions')
                    with Column(gap=1):
                        Muted("Style mix")
                        with Row(gap=2):
                            Badge('adventure: 1', variant='warning')
                            Badge('beach: 1', variant='default')
                with Tabs(value='august__beach'):
                    with Tab("Overview", value="overview"):
                        with Column(gap=5):
                            H3("Destinations by region")
                            PieChart(data=[{'name': 'Asia', 'value': 11}, {'name': 'Africa', 'value': 1}], data_key="value", name_key="name", show_legend=True)
                            H3("Sets saved by month")
                            BarChart(data=[{'month': 'May', 'sets': 1}, {'month': 'August', 'sets': 1}], series=[ChartSeries(data_key="sets", label="Sets")], x_axis="month", show_legend=False)
                            H3("All saved sets")
                            with Row(gap=3):
                                Text('Month')
                                Text('Style')
                                Text('# countries')
                                Text('Saved at')
                            with Row(gap=3):
                                Text('May')
                                Text('adventure')
                                Text('6')
                                Text('2026-05-03 19:05:43Z')
                            with Row(gap=3):
                                Text('August')
                                Text('beach')
                                Text('6')
                                Text('2026-05-03 20:36:05Z')
                    with Tab('May · adventure', value='may__adventure'):
                        with Column(gap=4):
                            H2('May · adventure')
                            with Row(gap=3):
                                Badge('adventure', variant='warning')
                                Muted('trekking, hiking, extreme sports, off-beat trails')
                                Muted('6 destinations · saved 2026-05-03 19:05:43Z')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇳🇵')
                                            with Column(gap=1):
                                                H3('Nepal')
                                                Muted('Kathmandu · Asia (Southern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 29,911,840', variant="default")
                                            Badge('NPR (₨)', variant="success")
                                            Badge('Nepali', variant="warning")
                                        Text('Why: Offers excellent trekking conditions in the pre-monsoon season with manageable crowds and stunning Himalayan views.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇧🇹')
                                            with Column(gap=1):
                                                H3('Bhutan')
                                                Muted('Thimphu · Asia (Southern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 784,043', variant="default")
                                            Badge('BTN (Nu.)', variant="success")
                                            Badge('Dzongkha', variant="warning")
                                        Text('Why: Prime trekking season with clear skies and pleasant temperatures, offering unique cultural and adventure experiences.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇰🇬')
                                            with Column(gap=1):
                                                H3('Kyrgyzstan')
                                                Muted('Bishkek · Asia (Central Asia)')
                                        with Row(gap=2):
                                            Badge('pop 7,281,800', variant="default")
                                            Badge('KGS (с)', variant="success")
                                            Badge('Kyrgyz', variant="warning")
                                            Badge('Russian', variant="warning")
                                        Text('Why: May marks the start of the trekking and horse riding season in its vast, untouched mountain ranges with e-visa ease.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇱🇰')
                                            with Column(gap=1):
                                                H3('Sri Lanka')
                                                Muted('Sri Jayawardenepura Kotte · Asia (Southern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 21,763,170', variant="default")
                                            Badge('LKR (Rs  රු)', variant="success")
                                            Badge('Sinhala', variant="warning")
                                            Badge('Tamil', variant="warning")
                                        Text('Why: Ideal for hiking through tea plantations and national parks, with good weather for exploring its diverse landscapes.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇬🇪')
                                            with Column(gap=1):
                                                H3('Georgia')
                                                Muted('Tbilisi · Asia (Western Asia)')
                                        with Row(gap=2):
                                            Badge('pop 4,000,921', variant="default")
                                            Badge('GEL (₾)', variant="success")
                                            Badge('Georgian', variant="warning")
                                        Text('Why: Spring offers fantastic hiking opportunities in the Caucasus Mountains with a visa-on-arrival facility for Indians.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇻🇳')
                                            with Column(gap=1):
                                                H3('Vietnam')
                                                Muted('Hanoi · Asia (South-Eastern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 101,343,800', variant="default")
                                            Badge('VND (₫)', variant="success")
                                            Badge('Vietnamese', variant="warning")
                                        Text('Why: Northern Vietnam is perfect for trekking through rice terraces and exploring caves, with an e-visa for convenient entry.')
                    with Tab('Aug · beach', value='august__beach'):
                        with Column(gap=4):
                            H2('August · beach')
                            with Row(gap=3):
                                Badge('beach', variant='default')
                                Muted('coast/island getaways, water sports, snorkeling, diving')
                                Muted('6 destinations · saved 2026-05-03 20:36:05Z')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇲🇻')
                                            with Column(gap=1):
                                                H3('Maldives')
                                                Muted('Malé · Asia (Southern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 515,132', variant="default")
                                            Badge('MVR (.ރ)', variant="success")
                                            Badge('Maldivian', variant="warning")
                                        Text('Why: August offers a good balance of sun and occasional showers, with excellent snorkeling and diving.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇹🇭')
                                            with Column(gap=1):
                                                H3('Thailand')
                                                Muted('Bangkok · Asia (South-Eastern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 65,859,640', variant="default")
                                            Badge('THB (฿)', variant="success")
                                            Badge('Thai', variant="warning")
                                        Text("Why: While it's the monsoon season, many islands in the Gulf of Thailand like Koh Samui still offer sunny spells and water activities.")
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇮🇩')
                                            with Column(gap=1):
                                                H3('Indonesia')
                                                Muted('Jakarta · Asia (South-Eastern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 284,438,782', variant="default")
                                            Badge('IDR (Rp)', variant="success")
                                            Badge('Indonesian', variant="warning")
                                        Text('Why: August is part of the dry season in many popular Indonesian destinations, ideal for beach and water sports.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇵🇭')
                                            with Column(gap=1):
                                                H3('Philippines')
                                                Muted('Manila · Asia (South-Eastern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 114,123,600', variant="default")
                                            Badge('PHP (₱)', variant="success")
                                            Badge('English', variant="warning")
                                            Badge('Filipino', variant="warning")
                                        Text('Why: August falls within the dry season for many Philippine islands, perfect for exploring beaches and diving.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇲🇾')
                                            with Column(gap=1):
                                                H3('Malaysia')
                                                Muted('Kuala Lumpur · Asia (South-Eastern Asia)')
                                        with Row(gap=2):
                                            Badge('pop 34,231,700', variant="default")
                                            Badge('MYR (RM)', variant="success")
                                            Badge('English', variant="warning")
                                            Badge('Malay', variant="warning")
                                        Text('Why: The east coast of peninsular Malaysia is in its prime for beach activities and snorkeling in August.')
                            with Card():
                                with CardContent():
                                    with Column(gap=2):
                                        with Row(gap=3):
                                            H2('🇸🇨')
                                            with Column(gap=1):
                                                H3('Seychelles')
                                                Muted('Victoria · Africa (Eastern Africa)')
                                        with Row(gap=2):
                                            Badge('pop 122,729', variant="default")
                                            Badge('SCR (₨)', variant="success")
                                            Badge('Seychellois Creole', variant="warning")
                                            Badge('English', variant="warning")
                                            Badge('French', variant="warning")
                                        Text('Why: August is part of the drier, cooler season in Seychelles, offering pleasant weather for its stunning beaches and marine life.')
